### ISSUE TITLE
Slight inaccuracy in comparing Google's monolith source repo

### ISSUE THREAD

**Issue by james** [platformland/playbook#2]
RE:

```
For this reason, Google have a single version control system for it’s code, which thousands of engineers across the organization have access to. It enables them to find, reuse and improve existing components.1 Estonia and the USA both emulated this, with publicly searchable repositories of source-code
```

I'm not sure if this undermines your point or not, but the interesting thing about Google's source repository is that it is not just available to all Google employees, but that the repo is just that, a single repo: https://cacm.acm.org/magazines/2016/7/204032-why-google-stores-billions-of-lines-of-code-in-a-single-repository/fulltext

It would be the equivalent of if all public sector organisations in a country kept all their code in a single GitHub repository. It blows my mind how Google do this and that it works (although they did have to build their own proprietary CVS to do it), and proposing that the public sector do this would be incredibly bold. But it's not what https://code.gov is doing, or I imagine what Estonia is doing (although I can't log in). They, and pretty much everyone else in the world is modelling the open source world by creating library updates and API versioning.

This may be being a bit pedantic about what we mean by "repository", but thought I'd mention it.

**Comment by richardjpope** [comment]
I've reworded it to make clearer
